config/routes.rb
Rails.application.routes.draw do

  get 'media/show_media', to: "media#show_media", as: "media/show_media"

  get 'media/media_showed', to: "media#media_showed", as: "media/media_showed"

  
  resources :registries

  resources :media

  root 'welcome#index'

  post 'media/get_media', to: "media#get_media", as: "media/get_media"

  post 'media/approve_media', to: "media#approve_media", as: "media/approve_media"

  post 'media/disapprove_media', to: "media#disapprove_media", as: "media/disapprove_media"

  post 'media/showed', to: "media#showed", as: "media/showed"

end

app/models/registry.rb
class Registry < ActiveRecord::Base
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: [:show, :edit, :update, :destroy]

  # GET /registries
  # GET /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registry_params
      params.require(:registry).permit(:last_registry)
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= form_for(@registry) do |f| %>
  <% if @registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
      <% @registry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_registry %><br>
    <%= f.date_select :last_registry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Editing registry</h1>

<%= render 'form' %>

<%= link_to 'Show', @registry %> |
<%= link_to 'Back', registries_path %>

app/views/registries/index.html.erb
<h1>Listing registries</h1>

<table>
  <thead>
    <tr>
      <th>Last registry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registries.each do |registry| %>
      <tr>
        <td><%= registry.last_registry %></td>
        <td><%= link_to 'Show', registry %></td>
        <td><%= link_to 'Edit', edit_registry_path(registry) %></td>
        <td><%= link_to 'Destroy', registry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registry', new_registry_path %>

app/views/registries/new.html.erb
<h1>New registry</h1>

<%= render 'form' %>

<%= link_to 'Back', registries_path %>

app/views/registries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last registry:</strong>
  <%= @registry.last_registry %>
</p>

<%= link_to 'Edit', edit_registry_path(@registry) %> |
<%= link_to 'Back', registries_path %>