config/routes.rb
Rails.application.routes.draw do

  get 'media/show_media', to: "media#show_media", as: "media/show_media"

  get 'media/media_showed', to: "media#media_showed", as: "media/media_showed"

  
  resources :registries

  resources :media

  root 'welcome#index'

  post 'media/get_media', to: "media#get_media", as: "media/get_media"

  post 'media/approve_media', to: "media#approve_media", as: "media/approve_media"

  post 'media/disapprove_media', to: "media#disapprove_media", as: "media/disapprove_media"

  post 'media/showed', to: "media#showed", as: "media/showed"

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy]

  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media/get_media.json
  def get_media
    Medium.save_media
    @media_to_show = Array.new
    @media_to_show = Medium.where("approve_state = ? AND show_state = ?", "Por Aprobación", "No Mostrado").order(created_at: :desc)
    respond_to do |format|
      format.json { render json: @media_to_show } 
    end
  end
  
  # POST /media/approve_media
  def approve_media
    id = params[:id]
    origin = params[:origin]
    media=Medium.find_by("id_media = ? AND social_net_origin =?", id, origin)
    media.approve_state = "Aprobado"
    respond_to do |format|
      if (media.save)
        format.html {render json: "Completo"}
      else
        format.html {render json: "Error"}
      end
    end
  end

  def disapprove_media
    id = params[:id]
    origin = params[:origin]
    media=Medium.find_by("id_media = ? AND social_net_origin =?", id, origin)
    media.approve_state = "No Aprobado"
    respond_to do |format|
      if (media.save)
        format.html {render json: "Completo"}
      else
        format.html {render json: "Error"}
      end
    end
  end

  def showed
    id = params[:id]
    origin = params[:origin]
    media=Medium.find_by("id_media = ? AND social_net_origin =?", id, origin)
    media.show_state = "Mostrado"
    respond_to do |format|
      if (media.save)
        format.html {render json: "Completo"}
      else
        format.html {render json: "Error"}
      end
    end
  end


  def show_media
    @media_to_show = Array.new
    @media_to_show = Medium.where("approve_state = ? AND show_state = ?", "Aprobado", "No Mostrado")
    @media_to_show = @media_to_show.shuffle
    respond_to do |format|
      format.html { }
      format.json { render json: @media_to_show } 
    end
  end

  def media_showed
    @media_showed = Array.new
    @media_showed = Medium.where("approve_state = ? AND show_state = ?", "Aprobado", "Mostrado")
    respond_to do |format|
      format.html { }
      format.json { render json: @media_showed } 
    end
  end
  
  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url, notice: 'Medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:id_media, :user, :text, :image_url, :approve_state, :show_state, :social_net_origin, :media_created_at)
    end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.erb
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_media %><br>
    <%= f.text_field :id_media %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :approve_state %><br>
    <%= f.text_field :approve_state %>
  </div>
  <div class="field">
    <%= f.label :show_state %><br>
    <%= f.text_field :show_state %>
  </div>
  <div class="field">
    <%= f.label :social_net_origin %><br>
    <%= f.text_field :social_net_origin %>
  </div>
  <div class="field">
    <%= f.label :media_created_at %><br>
    <%= f.date_select :media_created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table>
  <thead>
    <tr>
      <th>Id media</th>
      <th>User</th>
      <th>Text</th>
      <th>Image url</th>
      <th>Approve state</th>
      <th>Show state</th>
      <th>Social net origin</th>
      <th>Media created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= medium.id_media %></td>
        <td><%= medium.user %></td>
        <td><%= medium.text %></td>
        <td><%= medium.image_url %></td>
        <td><%= medium.approve_state %></td>
        <td><%= medium.show_state %></td>
        <td><%= medium.social_net_origin %></td>
        <td><%= medium.media_created_at %></td>
        <td><%= link_to 'Show', medium %></td>
        <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
        <td><%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id media:</strong>
  <%= @medium.id_media %>
</p>

<p>
  <strong>User:</strong>
  <%= @medium.user %>
</p>

<p>
  <strong>Text:</strong>
  <%= @medium.text %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @medium.image_url %>
</p>

<p>
  <strong>Approve state:</strong>
  <%= @medium.approve_state %>
</p>

<p>
  <strong>Show state:</strong>
  <%= @medium.show_state %>
</p>

<p>
  <strong>Social net origin:</strong>
  <%= @medium.social_net_origin %>
</p>

<p>
  <strong>Media created at:</strong>
  <%= @medium.media_created_at %>
</p>

<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/media/show_media.html.haml
.panelmediatoshow
.promo.text-center
	= image_tag ("banner-de-twetts.jpg")
.row.start
	.large-10.columns
		%br/
	.large-2.columns.animation
		.btn_animation.text-center#startanimation
			%p
				Iniciar Animación